In [8]:
# -*- encoding:utf-8 -*-

import tensorflow as tf

In [9]:
print(tf.__version__)

1.13.1


In [10]:
#Criando tensor objects
hello = tf.constant("Ola")
world = tf.constant("mundo")
type(hello)
print(hello)

Tensor("Const_6:0", shape=(), dtype=string)


In [11]:
#Tensorflow session
with tf.Session() as sess:
    result = sess.run(hello+world)
print(result)

b'Olamundo'


In [12]:
#Soma
a = tf.constant(10)
b = tf.constant(20)
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [14]:
#Para obter os resultados precisa usar dentro de uma sessão
with tf.Session() as sess:
    result = sess.run(a+b)
print(result)

30


In [17]:
#Operadores e funções do tensorflow
const = tf.constant(10)
fill_mat = tf.fill((4,4),10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)#usa a distribuicao normal
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)
my_ops = [myones, myrandn, myrandu, myzeros, fill_mat]

In [16]:
#Sessões interativas (interessante somente para o jupyter)
sess = tf.InteractiveSession()

In [20]:
for op in my_ops:
    print(sess.run(op))
    

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.4502705   1.0333042   0.65991586  1.3532593 ]
 [ 1.2013848   0.6118158   0.92533857  0.7054022 ]
 [ 0.7744437   1.3822939  -0.5857465   0.64268017]
 [-0.93749774 -0.00301301 -1.8868171  -0.3329898 ]]
[[0.7211758  0.28339577 0.02333617 0.4631014 ]
 [0.65854955 0.19614291 0.46449184 0.74183106]
 [0.58786225 0.49013042 0.43035364 0.9328456 ]
 [0.934788   0.4544525  0.38302338 0.11456478]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [25]:
#pegando a estrutura das constantes
a = tf.constant([ [1,2], 
                  [3,4] ])
b = tf.constant([ [10], [100] ])
a.get_shape()
b.get_shape()
result = tf.matmul(a,b)
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [26]:
result.eval()

array([[210],
       [430]], dtype=int32)